version: '2'
services:
    xinghaoapp-app:
        image: xinghaoapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://xinghaoapp-mysql:3306/xinghaoapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    xinghaoapp-mysql:
        extends:
            file: mysql.yml
            service: xinghaoapp-mysql
